---
# Needed for add-apt-repository
- name: Install python-software-properties
  apt: pkg=python-software-properties state=installed update-cache=yes


- name: Add repository key
  #apt_key: data="{{ lookup('file', 'ACCC4CF8.asc') }}"  state=present
  apt_key: url='http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc'  state=present

- name: Add PostgreSQL repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

 

  